[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "minddistrict.settings"
python_files = "tests.py test_*.py *_tests.py"
addopts = "--strict-markers"
django_debug_mode = "keep"

[tool.pycln]
all = true

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.black]
target-version = ['py311']
